# Generated by Django 2.2 on 2019-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='brand_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='fasten_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='material',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
